### ISSUE TITLE
Unable to install Plugin

### ISSUE THREAD

**Issue by 1n5aN1aC** [MoonshineSG/OctoPrint-Switch#1]
I have so far been unable to install the plugin, which I've been quite interested in for printer on/off functions integrating with Nautilus.

Octoprint just does the following:

```
Installing plugin from https://github.com/MoonshineSG/OctoPrint-Switch/archive/master.zip...
/home/pi/oprint/bin/python -m pip install https://github.com/MoonshineSG/OctoPrint-Switch/archive/master.zip
Collecting https://github.com/MoonshineSG/OctoPrint-Switch/archive/master.zip
Downloading https://github.com/MoonshineSG/OctoPrint-Switch/archive/master.zip
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ZenKOR-build/
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/tmp/pip-ZenKOR-build/setup.py'

----------------------------------------
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Done!
```

Any ideas?

Octoprint Version 1.3.0rc1 (rc/devel branch)

**Comment by MoonshineSG** [comment]
Yes, the plugin doesn't have a setup file. The only way it works is if you install manually. I'll do one by end of today and you can retry

**Comment by 1n5aN1aC** [comment]
Oh wow awesome!

Let me know and I'd be glad to try it again!

I could do it manually as well if you would prefer, but an actual plugin installer support would be epic!

**Comment by MoonshineSG** [comment]
you can try now

**Comment by 1n5aN1aC** [comment]
It seems to work now! 

Not able to test it yet, since I'm still having problems connecting the
app, but I expect to be messing with that tonight.

**Comment by 1n5aN1aC** [comment]
EDIT:  I think it's working, the buttons have appeared!

**Comment by MoonshineSG** [comment]
glad to hear that. just make sure the actions work as well... :D

**Comment by 1n5aN1aC** [comment]
Oh, it's definitely working.  The LED controls the printer.  xD

I'll have to configure that this weekend!
