### ISSUE TITLE
Suggestion:  add config file toGUI like Octoprint-Mobile

### ISSUE THREAD

**Issue by 1n5aN1aC** [MoonshineSG/OctoPrint-Switch#2]
Having the config file as part of the GUI would be nice like you did with Octoprint-Mobile.

Just a suggestion.  If it's not worth it for you, I can get by with SSH-ing in.  :)

**Comment by 1n5aN1aC** [comment]
Ahh, it's hardcoded.
Correction suggestion:  have a config file.

Then again, I can just change which pin I have it plugged into.  :)

**Comment by MoonshineSG** [comment]
Yes, hardcoded. Like all my plugins this was done to serve my own needs and has evolved, or better said still evolving. I can move it to the config file. 
Since this is something you shouldn't often change, it's not worth having it in settings. 
I'll do an update with the config soon.

**Comment by MoonshineSG** [comment]
you can try it now
