### ISSUE TITLE
Impossible power on from app

### ISSUE THREAD

**Issue by Diolum** [MoonshineSG/OctoPrint-Switch#4]
Hello 
Why i'm only able to turn on the printer from the Nautilus app?(the button is blurred)
I've fix my problem with puting on the led button the same gpio as the power pin.
Do you have a fix for that ?
Thanks
(Sorry i'm french)

**Comment by Diolum** [comment]
Sorry "turn off my printer"

**Comment by MoonshineSG** [comment]
No need to apologise for being French. It wasn't your choice.   :P  


So, to understand, the OFF button doesn't work ? How about other buttons ?  Can you see if there's any error message in the logs ?

**Comment by Diolum** [comment]
No ,sorry power it on from the app :p
This is the problem :
https://imgur.com/gallery/aAEuK
And the only way i make it work is by assign the led gpio to the same gpio as the power but now i'm not able to use my led bar anymore cause it's act like the power button now.

**Comment by MoonshineSG** [comment]
The power is disabled while the printer is not connected (the USB provides enough power to the board to allow it to boot)

**Comment by Diolum** [comment]
Haaa
I will explain you my setup:
I have an atx power suply.
I use the 5v sb for powering the pi.
I've take a otg cable and remove the 5v rail and connectes it to the motherboard of my printer so my screen does not stay on all the time.
I previously use psu-control to turn on the psu via the psu-on cable of the atx connector with an photocoupler 
That completely turn on the printemps and the screen.
This setup work fine.
And i've discover the naulilus app that Make Soooo Much more that all the other apps.
And decide to use octopint_switch and i can't use it as before.

**Comment by Diolum** [comment]
This is my setup:
http://diolum.free.fr/projets/octopi-dagoma/tutooctopi.html

**Comment by MoonshineSG** [comment]
I see... you can’t connect until you turn on the printer and you can’t turn on printer until you connect...  Right?
indeed a problem... 
Let me make some changes to solve your case (and maybe others as well)
I’ll need a couple of days ...

**Comment by Diolum** [comment]
Tanks a lot :)
And happy new years. :p

**Comment by MoonshineSG** [comment]
test something for me...

find the file called "nautilus_switch_plugin.jinja2". it should be under `~/oprint/local/lib/python2.7/site-packages/octoprint_nautilus/templates` or similar

Look for the line 

`<button type="button"  class="btn btn-default" data-bind="click: buttons.togglePower, enable: printer.ready, visible: !printer.inProgress()"><span class="fa  fa-lg fa-power-off" data-bind="style: { color: printer.power()?'#17b566':'#ed2b36' }"></span> Power</button>`

and remove the `enable: printer.ready,`

it will be: `<button type="button"  class="btn btn-default" data-bind="click: buttons.togglePower, visible: !printer.inProgress()"><span class="fa  fa-lg fa-power-off" data-bind="style: { color: printer.power()?'#17b566':'#ed2b36' }"></span> Power</button>`

refresh the page (shake the device ) and see if it helps... (as a temporary solution until I have time for a proper fix)

**Comment by Diolum** [comment]
Done but after restart the pi nothing change https://youtu.be/TvShKIUMl80

**Comment by MoonshineSG** [comment]
you don't need to restart the PI. you need to reload the UI on the iPhone. that can be done by shaking the device (while nautilus is running) - you will notice a vibration of the UI when it's refreshed.

**Comment by Diolum** [comment]
Thanks it work perfectly
You're the best.

**Comment by MoonshineSG** [comment]
until there is a permanent fix, you need to remember to make the changes after any plugin updates

**Comment by MoonshineSG** [comment]
Btw, if you enjoy Nautilus, a positive review on AppStore would be much appreciated. Thanks.

**Comment by Diolum** [comment]
That's done, 5 stars because you deserve it. :p
